# Generated by Django 5.2.3 on 2025-06-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(default='All Items Available', max_length=200),
            preserve_default=False,
        ),
    ]
