# Generated by Django 5.2.3 on 2025-07-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_item_status_alter_item_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
